require 'rails/generators/test_case'
require 'generators/better_exception_app/static_error_page/static_error_page_generator'

class StaticErrorPageGeneratorTest < Rails::Generators::TestCase
  tests BetterExceptionApp::StaticErrorPageGenerator
  destination File.expand_path('../../tmp/generator', File.dirname(__FILE__))
  setup :prepare_destination

  test 'error page generated by number' do
    run_generator %w{500}
    assert_file 'public/errors/500.html', /body/
    assert_file 'public/errors/500.html', /problem has occurred/
  end

  test 'error page generated by name' do
    run_generator %w{internal_server_error}
    assert_file 'public/errors/internal_server_error.html', /body/
    assert_file 'public/errors/internal_server_error.html', /problem has occurred/
  end

end
